### ISSUE TITLE
Issue with reproducing Create Rules section

### ISSUE THREAD

**Issue by Mahendra114027** [mhahsler/arulespy#2] opened 2023-05-19 15:11 UTC
Hi,

I am getting this error while trying out the create rules part from the [tutorial](https://mhahsler.github.io/arulespy/examples/arulesViz.html#Create-Rules). Is there something missing which needs to be done for this to work?

```AttributeError: module 'arulespy.arules' has no attribute 'set'```

Correct me if I am wrong here. I switched the arules.set() call with just maths set() call. Thought it would work as it requires a set there. But now the encode attributes is not accessible/missing.

```AttributeError: module 'arulespy.arules' has no attribute 'encode'```

Attached is a screenshot for reference.

![image](https://github.com/mhahsler/arulespy/assets/20869926/6d811e20-6443-4c76-b358-fc43f03a2739)

System Details:
- Ubuntu 22.04.02 LTS
- R version 4.3.0
- Python 3.10
- arulespy 0.0.2

**Comment by Mahendra114027** [comment] 2023-05-19 16:28
Thanks!!

**Comment by mhahsler** [comment] 2023-05-21 01:19
Duplicate of #1

**Closed by mhahsler** 2023-05-21 01:19 UTC
